keystore = "/path/to/keystore"

[home]
account = "0x547aff14210b6a72e106e27f34c626762f3c4761"
required_confirmations = 0
rpc_host = "http://rpc.host.for.home"
rpc_port = 8545
password = "home_password.txt"

[foreign]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
required_confirmations = 0
rpc_host = "https://rpc.host.for.foreign"
rpc_port = 443

[authorities]
accounts = [
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
]

[transactions]
home_deploy = { gas = 1000000, gas_price = 1000000000 }
foreign_deploy = { gas = 3000000, gas_price = 1000000000 }
deposit_relay = { gas = 100000, gas_price = 1000000000 }
