[home]
account = "0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"
ipc = "./examples/parity_POA_simple/jsonrpc.ipc"
required_confirmations = 0
request_timeout = 360

[home.contract]
bin = "contracts/EthereumBridge.bin"

[foreign]
account = "0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
ipc = "./examples/parity_POA_2_simple/jsonrpc.ipc"
required_confirmations = 0
request_timeout = 360

[foreign.contract]
bin = "contracts/KovanBridge.bin"

[authorities]
accounts = [
	"0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
]
required_signatures = 1

[transactions]
home_deploy = { gas = 3000000, gas_price = 21000000000 }
foreign_deploy = { gas = 3000000, gas_price = 21000000000 }
deposit_relay = { gas = 100000 }