keystore = "/path/to/keystore"

[home]
account = "0x547aff14210b6a72e106e27f34c626762f3c4761"
required_confirmations = 0
rpc_host = "http://rpc.host.for.home"
rpc_port = 8545
password = "home_password.txt"
gas_price_oracle_url = "https://gasprice.poa.network"
gas_price_speed = "instant"
default_gas_price = 10_000_000_000 # 10 GWEI

[foreign]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
required_confirmations = 0
rpc_host = "https://rpc.host.for.foreign"
rpc_port = 443
default_gas_price = 5_000_000_000 # 5 GWEI

[authorities]
accounts = [
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
]
required_signatures = 1

[transactions]
home_deploy = { gas = 1000000 }
foreign_deploy = { gas = 3000000 }
deposit_relay = { gas = 100000 }
