[parity]
chain = "kovan"
base_path = "./examples/parity_kov"

[account]
unlock = ["0x00dB9af45C6f241432F2cBE412c6969cB7778d98"]
password = ["examples/parity_password_kovan"]

[network]
port = 30333

[rpc]
port = 8555

[websockets]
port = 8556

[mining]
engine_signer = "0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
