# Sokol branch

[parity]
chain = "examples/parity_spec_oracles.json"
base_path = "./examples/parity_ora"

[network]
nat="extip:194.186.171.38"
reserved_peers="./examples/oracles_reserved_peers"
port = 30300
discovery=true

[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
interface = "0.0.0.0"
port = 8180
[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[dapps]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8080

[account]
#unlock = ["0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"]
#password = ["examples/parity_password_POA_private"]
unlock = ["0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"]
password = ["examples/parity_password_oracles"]

#[mining]
#engine_signer = "0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"
#reseal_on_txs = "all"
#usd_per_tx = "0"
#reseal_min_period = 0

#[misc]
#logging="chain=trace,engine=trace,miner=trace,own_tx=trace,poa=trace,signer=trace,txqueue=trace"